version: "3"
services:
  web:
    # Replace with username/repo:tag of your docker image
    image: paulitrix/hello:gettingstarted
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:


